# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputContent', models.TextField()),
                ('ratio', models.CharField(max_length=10)),
                ('outputContent', models.TextField()),
            ],
        ),
    ]
